version: "3.9"
services:
  localstack:
    container_name: c7n-challenge-localstack
    image: localstack/localstack:latest
    environment:
      SERVICES: "sqs,s3,dynamodb"
    ports:
      - "4566:4566"

