apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    foo: foo
    bar: bar
spec:
  serviceAccount: cluster-admin
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token
          expirationSeconds: 7200
          audience: vault
