apiVersion: v1
kind: Pod
metadata:
  name: c7n-challenge-raw-nginx
  namespace: c7n
spec:
  containers:
    - name: nginx-raw
      image: nginx:1.14.2
      ports:
        - containerPort: 80
--- 

apiVersion: v1
kind: Pod
metadata:
  name: c7n-challenge-nginx-host-path
  namespace: c7n
  labels:
    foo: bar
    bar: baz
spec:
  volumes:
    - name: c7n-website-storage
      hostPath:
        path: /tmp/nginx
        type: DirectoryOrCreate

  containers:
    - name: nginx-host
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      volumeMounts:
         - name: c7n-website-storage
           mountPath: /mnt/http

